Стилизация
htmlacademy-htmlcss/1038843-sedona-30 pull request #6
Opened 2021-02-02 11:39 UTC by RomaBond

2021-02-02 21:59 UTC, a-omarova requested changes

2021-02-02 21:59 UTC, a-omarova commented on index.html
>    				<li><a href="blank.html">Информация</a></li>
Классы должны быть у каждого элемента по-хорошему. Максимум его не может быть на последнем теге в цепочке, но и то я бы советовала пользоваться таким в очень редких случаях

2021-02-02 21:59 UTC, a-omarova commented on index.html
> +  					<a class="soacial-button" href="#">Твиттер</a>
опечатка в слове social

2021-02-02 21:59 UTC, a-omarova commented on style.css
> +	--basic: #F2F2F2;
одинаковая переменная для стольких значений? в этом случае будет использоваться только последнее ее значение

2021-02-02 21:59 UTC, a-omarova commented on style.css
> +	font-family: "PT Sans";
не указаны альтернативные шрифты и тип семейства

2021-02-02 21:59 UTC, a-omarova commented on style.css
> +}
C ссылок не убраны подчеркивания

2021-02-02 21:59 UTC, a-omarova commented on style.css
> +input {
глобальные стили задавать можно только для картинок и ссылок https://up.htmlacademy.ru/htmlcss/30/criteries#d25

2021-02-02 21:59 UTC, a-omarova commented on style.css
> +}
у блоков где фоном идет картинка тоже должен быть фоновый цвет
https://up.htmlacademy.ru/htmlcss/30/criteries#d10

2021-02-02 21:59 UTC, a-omarova commented on style.css
> +}
Цвет у ссылок тоже не задан

2021-02-02 21:59 UTC, a-omarova commented on style.css
> +}
Нет состояний интерактивных элементов

2021-02-02 21:59 UTC, a-omarova commented on style.css
> +form label {
глобальные стили использовать нельзя

2021-02-02 21:59 UTC, a-omarova commented on style.css
> +	src: url("../fonts/PTSans-Bold.woff2") format("woff2"),
пути до шрифтов ведут совсем не туда где лежат шрифты. И нужно переместить файл со стилями в папку css

2021-02-02 21:59 UTC, a-omarova commented on style.css
> +root {
селектор указан не правильно https://developer.mozilla.org/ru/docs/Web/CSS/:root

2021-02-03 08:46 UTC, RomaBond commented on index.html
>    				<li><a href="blank.html">Информация</a></li>
классы добавить всем элементам где их нет ? или что то не понял

2021-02-03 09:56 UTC, RomaBond commented on style.css
> +	font-family: "PT Sans";
в макете не прописано дополнительные шрифты 
как узнать ?

2021-02-03 23:05 UTC, a-omarova commented on index.html
>    				<li><a href="blank.html">Информация</a></li>
да классы нужны всем элементам

2021-02-03 23:13 UTC, a-omarova requested changes

2021-02-03 23:13 UTC, a-omarova commented on css/style.css
> +	    url("../fonts/PTSans.woff") format("woff");
не исправлены пути

2021-02-03 23:13 UTC, a-omarova commented on css/style.css
> +	font-family: "PT Sans";
нет доп шрифта и типа семейства

2021-02-03 23:13 UTC, a-omarova commented on style.css
> +	font-family: "PT Sans";
Погуглить)

2021-02-03 23:13 UTC, a-omarova commented on style.css
> +}
у кнопок все еще есть лишняя рамка

2021-02-03 23:13 UTC, a-omarova commented on index.html
> +    <link rel="stylesheet" href="normalize.css">
normalize по такому пути нет

2021-02-03 23:13 UTC, a-omarova commented on index.html
> +    <link rel="stylesheet" href="style.css">
файл styles теперь в двух экземплярах, один надо удалить и прикрепить тот что нужно

2021-02-04 20:06 UTC, a-omarova commented on style.css
> +	src: url("../fonts/PTSans-Bold.woff2") format("woff2"),
пути до шрифтов не правильные

2021-02-04 20:08 UTC, a-omarova commented
Все еще нету фонового цвета для блоков
https://up.htmlacademy.ru/htmlcss/30/criteries#d10

2021-02-04 20:10 UTC, a-omarova requested changes

2021-02-04 20:10 UTC, a-omarova commented on css/style.css
> +	    url("fonts/PTSans.woff") format("woff");
пути все еще не правильные

2021-02-04 20:10 UTC, a-omarova commented on css/style.css
> +root {
селектор не исправлен

2021-02-04 20:10 UTC, a-omarova commented on css/style.css
> +	font-family: "PT Sans" "Roboto" "Sans-serif";
это не правильное значение типа семейства. Глянь в консоли разработчика

2021-02-04 20:11 UTC, a-omarova commented
нужно привести в порядок выравнивание кода, это один из критериев

2021-02-07 08:43 UTC, a-omarova commented on css/style.css
> +	font-family: "PT Sans" "PT Mono" "PT Serif";
1. между шрифтами обязательно должна быть запятая,
2. тип семейсва не указан https://htmlacademy.ru/courses/309/run/5

2021-02-07 18:48 UTC, merged